"""Pseudonymous return codes: coming back across the retention interval.

The problem
-----------
The retention probe opens seven days after the immediate one. A browser cookie
frequently does not survive that: a shared lab machine is reimaged, a private
window is closed, a phone clears site data. Without a way back, retention
attrition would be an artifact of cookie lifetime rather than of anything the
study is measuring.

The mechanism
-------------
At enrollment the participant is issued one high-entropy opaque code and shown
it once. Only a **keyed digest** of it is stored. Presenting the code later
re-binds the current browser session to the existing enrollment; the
``participant_id``, the allocated arm and every recorded response are untouched.

Why this is not personal data
-----------------------------
The code is generated by :func:`secrets.token_urlsafe` and is derived from
nothing: not the ``participant_id``, not the Flask ``session_id``, not a name,
not a timestamp, not the allocation slot. It identifies an enrollment and
nothing else, and it cannot be inverted into any of them. It is a *continuity
credential*, and it is treated as a credential throughout: never logged, never
persisted in the clear, never placed in a URL or a query string, and never
exported.

Why the digest is keyed
-----------------------
An unkeyed hash of a code is still enumerable by anyone who obtains the table
and can guess the alphabet and length. Keying with the study secret means a
copy of the database alone is not enough. The digest stays deterministic, so it
remains a unique, indexable lookup key -- which is the whole reason a keyed
digest is used here rather than a per-row salted password hash.

Purity
------
Standard library only: ``hmac``, ``hashlib``, ``secrets``.
"""

import hashlib
import hmac
import secrets

from .errors import StudyConfigurationError

#: The environment variable an operator sets for the continuity digest key.
#: Deliberately distinct from :data:`study.assignment.SECRET_ENV_VAR`: arm
#: allocation and return-code continuity are separate security domains --
#: knowing one must never help an attacker with the other -- so they are keyed
#: with independent secrets rather than one key shared across both purposes.
SECRET_ENV_VAR = "REWINDSEC_STUDY_CONTINUITY_SECRET"

#: Bytes of entropy in a return code. 24 bytes is 192 bits, rendered by
#: ``token_urlsafe`` as 32 URL-safe characters. Deliberately not a short numeric
#: PIN: a guessable code would let one participant reach another's enrollment.
RETURN_CODE_BYTES = 24

#: Length of the rendered code, used by validation and by the tests that assert
#: the entropy claim rather than trusting the comment above it.
RETURN_CODE_LENGTH = 32

#: Domain separator: a return-code digest can never coincide with an allocation
#: digest derived from the same secret.
_PERSONALISATION = b"rewindsec-study-return-code-v1"

#: The characters ``token_urlsafe`` can emit.
_ALPHABET = frozenset(
    "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_")


def require_secret(secret):
    """Return the continuity secret as bytes, or fail closed.

    A separate check from :func:`study.assignment.require_secret` so the error
    names the right environment variable, and so the two domains never share
    fail-closed logic by accident either.
    """
    if not secret:
        raise StudyConfigurationError(
            "research mode requires a study continuity secret; set {0}"
            .format(SECRET_ENV_VAR))
    return secret.encode("utf-8") if isinstance(secret, str) else bytes(secret)


def new_return_code():
    """A fresh opaque return code. The only place a raw code is created."""
    return secrets.token_urlsafe(RETURN_CODE_BYTES)


def looks_like_code(candidate):
    """Cheap shape check before a digest is computed.

    Rejects an obviously malformed submission without doing keyed work, and --
    more importantly -- bounds the input, so a multi-megabyte POST body is never
    hashed.
    """
    return (isinstance(candidate, str)
            and 16 <= len(candidate) <= 64
            and all(character in _ALPHABET for character in candidate))


def code_digest(secret, code):
    """The stored form of a return code: keyed, hex, deterministic.

    Raises :class:`~study.errors.StudyConfigurationError` through
    :func:`~study.assignment.require_secret` when research mode has no secret,
    so a digest can never be computed under an empty key.
    """
    key = require_secret(secret)
    return hmac.new(key, _PERSONALISATION + b"|" + code.encode("utf-8"),
                    hashlib.sha256).hexdigest()


def digests_match(left, right):
    """Constant-time comparison of two stored digests."""
    if not isinstance(left, str) or not isinstance(right, str):
        return False
    return hmac.compare_digest(left, right)


__all__ = [
    "SECRET_ENV_VAR", "require_secret",
    "RETURN_CODE_BYTES", "RETURN_CODE_LENGTH", "new_return_code",
    "looks_like_code", "code_digest", "digests_match",
]
