"""Deterministic, allow-listed rendering of synthetic state for learners.

A learner is never shown a raw JSON dump, and never shown prose generated by a
language model. Every sentence on the comparison page comes from a fixed table
keyed by ``(state pointer, value)`` in this module, so the same stored result
always renders the same words and a reviewer can read the complete vocabulary
in one file.

The table is an **allow-list**. A state field that is added to the scenario
later, but not described here, produces nothing at all rather than leaking an
internal key name or an unreviewed value into the UI.

Milestone R4 added a second scenario, so the *machinery* here (flattening,
ordering, negative suppression, difference rendering) is now shared and the
*vocabulary* is a parameter. A :class:`Vocabulary` bundles one scenario's
tables; ``describe_state`` and ``describe_difference`` default to the phishing
one, so every existing call site behaves exactly as before.
"""

from .phishing import PHISHING_SCENARIO_KEY, choice_labels
from .ransomware import (IMPACT_PROGRESSION, RANSOMWARE_SCENARIO_KEY,
                         ransomware_choice_labels)

#: ``pointer -> {value: sentence}``. Only these pointers are ever rendered, and
#: only for these exact values. ``None`` as a key means "the field is unset".
STATE_SENTENCES = {
    "identity.exposed": {
        True: "Synthetic credential was exposed",
        False: "No credential was exposed",
    },
    "account.synthetic_access": {
        True: "Synthetic account access succeeded",
        False: "No account access occurred",
    },
    "resource.accessed": {
        True: "A synthetic internal resource was accessed",
        False: "Internal resources were not reached",
    },
    "message.sender_inspected": {
        True: "The sender details were inspected",
        False: "The sender details were not inspected",
    },
    "message.verified_independently": {
        True: "The request was checked through a trusted channel",
        False: "The request was never checked through a trusted channel",
    },
    "message.reported": {
        True: "The suspicious message was reported",
        False: "The message was not reported",
    },
    "incident.created": {
        True: "A synthetic security incident was raised",
        False: "No incident was raised",
    },
    "evidence.sender_mismatch_visible": {
        True: "The sending domain did not match the service it claimed to be",
        False: "The sending domain was never examined",
    },
    "evidence.verification_outcome": {
        "request_not_legitimate": "The trusted channel confirmed the request "
                                  "was not legitimate",
        None: "No independent verification result was obtained",
    },
}

#: Pointers whose value is an allow-listed resource *key*, rendered by name.
#: Never a URL, host or path -- the state does not contain one.
RESOURCE_POINTER = "resource.key"

#: Order the outcome lines are presented in. Pointers absent from a given state
#: are skipped, so the list is a layout preference, not a requirement.
DISPLAY_ORDER = (
    "identity.exposed",
    "account.synthetic_access",
    "resource.accessed",
    "message.sender_inspected",
    "evidence.sender_mismatch_visible",
    "message.verified_independently",
    "evidence.verification_outcome",
    "message.reported",
    "incident.created",
)

#: Pointers whose *false* reading is only worth showing when something else in
#: the state makes the contrast meaningful. Keeping "No credential was exposed"
#: on a safe branch is useful; repeating every negative is noise.
NEGATIVE_WORTH_SHOWING = frozenset({
    "identity.exposed", "account.synthetic_access", "resource.accessed"})


class Vocabulary:
    """One scenario's complete rendering tables.

    ``sentences``  ``pointer -> {value: sentence}`` exact-match table.
    ``formatters`` ``pointer -> callable(value) -> str`` for readings whose
                   value is a count or an allow-listed list of synthetic
                   filenames, where an exact-match table cannot work. A
                   formatter is still fixed, reviewable code in this package;
                   it is never generated text.
    ``display_order``  the pointers rendered, in order. A pointer absent from
                   it is never shown.
    ``negative_worth_showing``  pointers whose ``False``/``None`` reading is
                   still worth a line because the contrast is meaningful.
    """

    def __init__(self, sentences, display_order, negative_worth_showing=(),
                 formatters=None):
        self.sentences = dict(sentences)
        self.display_order = tuple(display_order)
        self.negative_worth_showing = frozenset(negative_worth_showing)
        self.formatters = dict(formatters or {})

    def sentence_for(self, pointer, value):
        """The allow-listed sentence for one reading, or ``None``."""
        formatter = self.formatters.get(pointer)
        if formatter is not None:
            try:
                return formatter(value)
            except (TypeError, ValueError):
                # An unexpected value type is not described rather than
                # printed: an undescribed reading never reaches the UI.
                return None
        try:
            return self.sentences.get(pointer, {}).get(value)
        except TypeError:
            # Unhashable reading (a list where a scalar was described).
            return None


def _flatten(state, prefix=()):
    """Yield ``(pointer, value)`` for every leaf of a nested mapping."""
    if not isinstance(state, dict):
        return
    for key in sorted(state):
        value = state[key]
        path = prefix + (str(key),)
        if isinstance(value, dict):
            for item in _flatten(value, path):
                yield item
        else:
            yield ".".join(path), value


#: The default (phishing) vocabulary, assembled from the tables above so the
#: module-level constants stay the single source of truth.
PHISHING_VOCABULARY = Vocabulary(STATE_SENTENCES, DISPLAY_ORDER,
                                 NEGATIVE_WORTH_SHOWING)


def sentence_for(pointer, value, vocabulary=None):
    """The allow-listed sentence for one state reading, or ``None``.

    Unknown pointers and unknown values return ``None`` by design: an
    undescribed field is not printed.
    """
    return (vocabulary or PHISHING_VOCABULARY).sentence_for(pointer, value)


def describe_state(state, resources=None, vocabulary=None):
    """Render one resulting synthetic state as ordered learner-readable lines.

    ``resources`` is the application's synthetic-resource allow-list, used only
    to name an accessed resource. A key that is not in it is not rendered.
    """
    vocabulary = vocabulary or PHISHING_VOCABULARY
    readings = dict(_flatten(state or {}))
    lines = []
    for pointer in vocabulary.display_order:
        if pointer not in readings:
            continue
        value = readings[pointer]
        # A negative reading is shown only where the contrast is meaningful.
        # (The full negative vocabulary still exists above, because the
        # difference table needs to render both sides of every change.)
        if (value is False or value is None) and (
                pointer not in vocabulary.negative_worth_showing):
            continue
        sentence = vocabulary.sentence_for(pointer, value)
        if sentence is None:
            continue
        lines.append({"pointer": pointer, "value": value, "text": sentence,
                      "notable": bool(value)})

    key = readings.get(RESOURCE_POINTER)
    if key and resources and key in resources:
        lines.append({
            "pointer": RESOURCE_POINTER, "value": key, "notable": True,
            "text": "Resource reached: %s" % resources[key]["title"]})
    return lines


def describe_difference(difference, resources=None, vocabulary=None):
    """Render a stored :class:`~training.comparison.StateDiff` dict.

    Takes the persisted ``difference_json`` structure (already parsed) and
    returns one line per change that this module knows how to describe. Each
    line states what the factual branch produced and what the rewind branch
    produced, in that order -- never reordered so that the unsafe branch lands
    on a particular side.
    """
    vocabulary = vocabulary or PHISHING_VOCABULARY
    lines = []
    for change in (difference or {}).get("changes", []):
        pointer = change.get("pointer")
        before, after = change.get("from"), change.get("to")
        if pointer == RESOURCE_POINTER:
            if not resources:
                continue
            lines.append({
                "pointer": pointer,
                "your_path": ("Resource reached: %s" % resources[before]["title"]
                              if before in resources else "No resource reached"),
                "rewind_path": ("Resource reached: %s" % resources[after]["title"]
                                if after in resources else "No resource reached"),
            })
            continue
        your_path = vocabulary.sentence_for(pointer, before)
        rewind_path = vocabulary.sentence_for(pointer, after)
        if your_path is None and rewind_path is None:
            continue
        lines.append({"pointer": pointer,
                      "your_path": your_path or "Not applicable",
                      "rewind_path": rewind_path or "Not applicable"})
    return lines


#: ``scenario_key -> callable returning that scenario's choice_id -> label``.
#:
#: Keyed by scenario, deliberately. A choice id is scenario-*local*: two
#: scenarios may legitimately name a choice the same thing, and a lookup that
#: fell through to another scenario's table would silently turn choice ids into
#: globally unique identifiers and render the wrong label. Resolution therefore
#: never leaves the named scenario's own vocabulary.
CHOICE_LABEL_SOURCES = {
    PHISHING_SCENARIO_KEY: choice_labels,
    RANSOMWARE_SCENARIO_KEY: ransomware_choice_labels,
}


# -- the ransomware incident-response vocabulary (R4) ------------------------
#: Total size of the fixed synthetic dataset, so a count reads as "n of 5".
SYNTHETIC_FILE_TOTAL = len(IMPACT_PROGRESSION)


def _plural(count, singular, plural=None):
    return singular if count == 1 else (plural or singular + "s")


def _impacted_count(value):
    if isinstance(value, bool) or not isinstance(value, int):
        raise ValueError("impacted count must be an integer")
    return "%d of %d synthetic files impacted" % (value, SYNTHETIC_FILE_TOTAL)


def _available_count(value):
    if isinstance(value, bool) or not isinstance(value, int):
        raise ValueError("available count must be an integer")
    return "%d synthetic %s still available" % (value, _plural(value, "file"))


def _known_names(value):
    """Render a list of synthetic filenames, refusing anything unknown.

    The state is built from the fixed dataset, so this is a second gate rather
    than the first one: an unknown name is not printed at all.
    """
    if not isinstance(value, (list, tuple)):
        raise ValueError("file list must be a sequence")
    names = [name for name in value if name in IMPACT_PROGRESSION]
    if len(names) != len(value):
        raise ValueError("file list contains an unknown synthetic filename")
    return names


def _impacted_files(value):
    names = _known_names(value)
    if not names:
        return "No documents were impacted"
    return "Impacted %s: %s" % (_plural(len(names), "document"),
                                ", ".join(names))


def _available_files(value):
    names = _known_names(value)
    if not names:
        return "No documents remain available"
    return "Still available: %s" % ", ".join(names)


RANSOMWARE_STATE_SENTENCES = {
    "endpoint.isolated": {
        True: "The workstation was isolated from the network",
        False: "The workstation stayed connected to the network",
    },
    "endpoint.restarted": {
        True: "The workstation was restarted",
        False: "The workstation was not restarted",
    },
    "incident.reported": {
        True: "The incident was reported to the security team",
        False: "The incident was not reported",
    },
}

RANSOMWARE_FORMATTERS = {
    "files.impacted_count": _impacted_count,
    "files.available_count": _available_count,
    "files.impacted": _impacted_files,
    "files.available": _available_files,
}

RANSOMWARE_DISPLAY_ORDER = (
    "files.impacted_count",
    "files.available_count",
    "files.impacted",
    "endpoint.isolated",
    "endpoint.restarted",
    "incident.reported",
)

#: Every ransomware reading is worth showing in both directions: "the
#: workstation stayed connected" is exactly as informative as its opposite.
RANSOMWARE_NEGATIVE_WORTH_SHOWING = frozenset(RANSOMWARE_DISPLAY_ORDER)

RANSOMWARE_VOCABULARY = Vocabulary(RANSOMWARE_STATE_SENTENCES,
                                   RANSOMWARE_DISPLAY_ORDER,
                                   RANSOMWARE_NEGATIVE_WORTH_SHOWING,
                                   RANSOMWARE_FORMATTERS)


def choice_labels_for(scenario_key):
    """One scenario's ``choice_id -> label`` map, or an empty map.

    An unknown scenario key resolves to no vocabulary at all rather than to
    another scenario's, so a caller can never accidentally render a label that
    belongs to a different scenario.
    """
    source = CHOICE_LABEL_SOURCES.get(scenario_key)
    return dict(source()) if source is not None else {}


def label_for_choice(scenario_key, choice_id):
    """The display label for one scenario's choice id.

    Falls back to the choice id itself -- an intentionally neutral rendering --
    when the scenario key is unknown or the id is not one of that scenario's
    choices. It never searches another scenario's vocabulary.
    """
    return choice_labels_for(scenario_key).get(choice_id, choice_id or "")
